notifications:
  email: omi.devs@gmail.com

language: cpp

compiler: gcc

dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

  # cmake 3.11
  - wget https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz
  - tar -zxf cmake-3.11.4.tar.gz
  - cd cmake-3.11.4
  - ./bootstrap
  - make -s
  - sudo make install
  - cmake --version
  - cd ..

  # boost 1.67
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
  - tar -xzf boost_1_67_0.tar.gz
  - cd boost_1_67_0/
  - ./bootstrap.sh --with-libraries=program_options,filesystem,system
  - ./b2 -d0
  - sudo ./b2 install -d0

before_script:  
  - export PATH=/usr/local/bin:$PATH
  - cd ..
  - mkdir build
  - cd build
  - cmake ..

script: make
