notifications:
  email: omi.devs@gmail.com

language: cpp

compiler: gcc

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # g++
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - g++ --version

  # cmake
  - wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh
  - wget https://cmake.org/files/v3.12/cmake-3.12.1-SHA-256.txt
  - grep cmake-3.12.1-Linux-x86_64.sh cmake-3.12.1-SHA-256.txt | shasum -c -
  - sudo sh cmake-3.12.1-Linux-x86_64.sh --prefix=/usr/local --skip-license
  - /usr/local/bin/cmake --version

  # boost 1.67
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
  - tar -xzf boost_1_67_0.tar.gz
  - cd boost_1_67_0/
  - ./bootstrap.sh --with-libraries=program_options,filesystem,system
  - ./b2 -d0
  - sudo ./b2 install -d0
  - cd ..

before_script:
  - export PATH=/usr/local/bin:$PATH
  - mkdir build
  - cd build
  - cmake ..

script: make
