notifications:
  email: matthew.nam@gmail.com

language: cpp

compiler: gcc

dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - tar -xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - ./bootstrap.sh --prefix=. --with-libraries=program_options,filesystem,system
  - ./b2 -d0
  - ./b2 install -d0

before_script:  
  - cd ..
  - mkdir build
  - cd build
  - cmake ..

script: make
